name: Build and Release

on:
  push:
    branches:
      - "**"

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps + run download.js
        run: |
          npm i
          node .\.github\workflows\download.js

      - name: Prepare ZIP content
        run: |
          # Utwórz katalog
          New-Item -ItemType Directory -Force -Path release_root | Out-Null

          # Skopiuj wszystko oprócz release_root i .git
          Get-ChildItem -Force | Where-Object {
            $_.Name -ne "release_root" -and $_.Name -ne ".git"
          } | Copy-Item -Recurse -Force -Destination release_root

          # Spakuj
          Compress-Archive -Path release_root\* -DestinationPath release.zip -Force

      - name: Create tag name
        id: tag
        run: echo "tag=build-$($env:GITHUB_SHA.Substring(0,7))" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ github.event.head_commit.message }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
